# Generated by Django 5.2.4 on 2025-07-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdfs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="website",
        ),
    ]
