# Generated by Django 5.2.4 on 2025-07-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfs", "0002_remove_uploadedfile_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to="uploaded_files/"),
        ),
    ]
