# Generated by Django 5.2.4 on 2025-07-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfs", "0004_alter_uploadedfile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="filename",
            field=models.CharField(default="i love you", max_length=250),
            preserve_default=False,
        ),
    ]
