# Generated by Django 5.2.4 on 2025-07-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfs", "0005_uploadedfile_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
