# Generated by Django 5.2.4 on 2025-08-01 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfs", "0006_alter_uploadedfile_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="content",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(
                upload_to="uploaded_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
