# Generated by Django 5.2.4 on 2025-08-01 15:45

import django.core.validators
import pdfs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfs", "0007_uploadedfile_content_alter_uploadedfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(
                upload_to="uploaded_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    pdfs.validators.validate_file_size,
                ],
            ),
        ),
    ]
