# Generated by Django 5.2.4 on 2025-07-20 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfs", "0002_remove_uploadedfile_website"),
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="file",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pdfs.uploadedfile",
            ),
            preserve_default=False,
        ),
    ]
