# Generated by Django 5.2.4 on 2025-07-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0002_website_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="website",
            old_name="slug",
            new_name="url",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
