# Generated by Django 5.2.4 on 2025-07-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0003_rename_slug_website_url_delete_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("dark", "Dark"), ("light", "Light")],
                        default="dark",
                        max_length=20,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[("minimal", "Minimal"), ("creative", "Creative")],
                        default="minimal",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Theme Configuration",
                "verbose_name_plural": "Theme Configurations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Website Content",
                "verbose_name_plural": "Website Contents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="website",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Website",
                "verbose_name_plural": "Websites",
            },
        ),
        migrations.RemoveField(
            model_name="website",
            name="content",
        ),
        migrations.RemoveField(
            model_name="website",
            name="has_paid_download",
        ),
        migrations.RemoveField(
            model_name="website",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="website",
            name="type",
        ),
        migrations.AlterField(
            model_name="website",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
