# Generated by Django 5.2.4 on 2025-07-22 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0004_themeconfig_websitecontent_alter_website_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="content",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="websites",
                to="websites.websitecontent",
            ),
        ),
        migrations.AddField(
            model_name="website",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="websites",
                to="websites.themeconfig",
            ),
        ),
    ]
