# Generated by Django 5.2.4 on 2025-08-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "websites",
            "0006_themeconfig_name_themeconfig_user_website_unique_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="website",
            old_name="url",
            new_name="slug",
        ),
    ]
